stages:
  - test

variables:
  WORKON_HOME: .pipenv/venvs
  PIP_CACHE_DIR: .pipenv/pipcache

cache:
  key: pipenv
  paths:
    - .pipenv

test_job:
  stage: test
  image: python:3.10
  before_script:
    - python -m pip install --upgrade pipenv wheel
    - pipenv install --deploy --dev --ignore-pipfile
  script:
    - pipenv run -v test
